### ISSUE TITLE
Is it possible to add all cell voltages in your integration?

### ISSUE THREAD

**Issue by Karatzie** [Patrick762/hassio-bluetti-bt#141]
Hi Patrick,

I own a AC200MAX and use the HA with the Bluetti ADDON bluetti_mqtt.

[https://github.com/warhammerkid/bluetti_mqtt](url)

This ADDON delivers additional sensors from the Bluetti.
It is possible to add cell voltages and some additional sensors over the configuration yaml.
I have add this code in this file:
```
mqtt:
  sensor:
    - name: "AC200M SPG Zelle 01"
      unique_id: ac200mcell1
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[0] }}"
    - name: "AC200M SPG Zelle 02"
      unique_id: ac200mcell2
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[1] }}"
    - name: "AC200M SPG Zelle 03"
      unique_id: ac200mcell3
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[2] }}"
    - name: "AC200M SPG Zelle 04"
      unique_id: ac200mcell4
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[3] }}"
    - name: "AC200M SPG Zelle 05"
      unique_id: ac200mcell5
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[4] }}"
    - name: "AC200M SPG Zelle 06"
      unique_id: ac200mcell6
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[5] }}"
    - name: "AC200M SPG Zelle 07"
      unique_id: ac200mcell7
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[6] }}"
    - name: "AC200M SPG Zelle 08"
      unique_id: ac200mcell8
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[7] }}"
    - name: "AC200M SPG Zelle 09"
      unique_id: ac200mcell9
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[8] }}"
    - name: "AC200M SPG Zelle 10"
      unique_id: ac200mcell10
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[9] }}"
    - name: "AC200M SPG Zelle 11"
      unique_id: ac200mcell11
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[10] }}"
    - name: "AC200M SPG Zelle 12"
      unique_id: ac200mcell12
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[11] }}"
    - name: "AC200M SPG Zelle 13"
      unique_id: ac200mcell13
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[12] }}"
    - name: "AC200M SPG Zelle 14"
      unique_id: ac200mcell14
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[13] }}"
    - name: "AC200M SPG Zelle 15"
      unique_id: ac200mcell15
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[14] }}"
    - name: "AC200M SPG Zelle 16"
      unique_id: ac200mcell16
      icon: mdi:battery
      state_topic: "bluetti/state/AC200M-2204000267875/pack_details1"
      unit_of_measurement: "V"
      value_template: "{{ value_json.voltages[15] }}"
    - name: "AC200M AC Frequenz"
      unique_id: ac200macfrequenz
      icon: mdi:electron-framework
      state_topic: "bluetti/state/AC200M-2204000267875/internal_ac_frequency"
      unit_of_measurement: "hz"
      value_template: "{{ value_json }}"
    - name: "AC200M AC SPG"
      unique_id: ac200macspg
      icon: mdi:electron-framework
      state_topic: "bluetti/state/AC200M-2204000267875/internal_ac_voltage"
      unit_of_measurement: "V"
      value_template: "{{ value_json }}"
    - name: "AC200M Intern Power"
      unique_id: ac200minternalpower
      icon: mdi:electron-framework
      state_topic: "bluetti/state/AC200M-2204000267875/internal_power_one"
      unit_of_measurement: "W"
      value_template: "{{ value_json }}"
    - name: "AC200M AC Inverter Mode"
      unique_id: ac200macinvertermode
      icon: mdi:electron-framework
      state_topic: "bluetti/state/AC200M-2204000267875/ac_output_mode"
``` 

It would be a greate thing to add this sensors in your integration.

BR Andreas
